In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\mypc\appdata\roaming\python\python313\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mypc\appdata\roaming\python\python313\site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mypc\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mypc\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:

import pandas as pd
s=pd.Series([10,20,30,40])
s=pd.Series(['mahnoor','christible', 'hiba', 'ayesha', 'fatimah', 'tehreem'])
s

0       mahnoor
1    christible
2          hiba
3        ayesha
4       fatimah
5       tehreem
dtype: object

In [9]:
data_of_python_class={
    "name":['mahnoor','christible', 'hiba', 'ayesha', 'fatimah', 'tehreem'],
    "age":[10, 20, 90, 18, 77,1000]
}



df =pd.DataFrame(data_of_python_class)
df

         name   age
0     mahnoor    10
1  christible    20
2        hiba    90
3      ayesha    18
4     fatimah    77
5     tehreem  1000

In [13]:
df.index
df.columns

Index(['name', 'age'], dtype='object')

In [19]:
df.index=[0, 1,2,3,4,5]
df.columns=['name', 'age']

In [22]:
pd.read_csv("quran.csv")

,code,status,data.number,data.name,data.englishName,data.englishNameTranslation,data.numberOfAyahs,data.revelationType
0,200,OK,1,سُورَةُ ٱلْفَاتِحَةِ,Al-Faatiha,The Opening,7,Meccan
1,200,OK,6,سُورَةُ الأَنۡعَامِ,Al-An'aam,The Cattle,165,Meccan
2,200,OK,7,سُورَةُ الأَعۡرَافِ,Al-A'raaf,The Heights,206,Meccan
3,200,OK,10,سُورَةُ يُونُسَ,Yunus,Jonas,109,Meccan
4,200,OK,11,سُورَةُ هُودٍ,Hud,Hud,123,Meccan
...,...,...,...,...,...,...,...,...
109,200,OK,66,سُورَةُ التَّحۡرِيمِ,At-Tahrim,The Prohibition,12,Medinan
110,200,OK,76,سُورَةُ الإِنسَانِ,Al-Insaan,Man,31,Medinan
111,200,OK,98,سُورَةُ البَيِّنَةِ,Al-Bayyina,The Evidence,8,Medinan
112,200,OK,99,سُورَةُ الزَّلۡزَلَةِ,Az-Zalzala,The Earthquake,8,Medinan
113,200,OK,110,سُورَةُ النَّصۡرِ,An-Nasr,Divine Support,3,Medinan

In [24]:
pd.read_excel("quran.xlsx")

,code,status,data.number,data.name,data.englishName,data.englishNameTranslation,data.numberOfAyahs,data.revelationType
0,200,OK,1,سُورَةُ ٱلْفَاتِحَةِ,Al-Faatiha,The Opening,7,Meccan
1,200,OK,6,سُورَةُ الأَنۡعَامِ,Al-An'aam,The Cattle,165,Meccan
2,200,OK,7,سُورَةُ الأَعۡرَافِ,Al-A'raaf,The Heights,206,Meccan
3,200,OK,10,سُورَةُ يُونُسَ,Yunus,Jonas,109,Meccan
4,200,OK,11,سُورَةُ هُودٍ,Hud,Hud,123,Meccan
...,...,...,...,...,...,...,...,...
109,200,OK,66,سُورَةُ التَّحۡرِيمِ,At-Tahrim,The Prohibition,12,Medinan
110,200,OK,76,سُورَةُ الإِنسَانِ,Al-Insaan,Man,31,Medinan
111,200,OK,98,سُورَةُ البَيِّنَةِ,Al-Bayyina,The Evidence,8,Medinan
112,200,OK,99,سُورَةُ الزَّلۡزَلَةِ,Az-Zalzala,The Earthquake,8,Medinan
113,200,OK,110,سُورَةُ النَّصۡرِ,An-Nasr,Divine Support,3,Medinan

In [26]:
pd.read_csv("https://raw.githubusercontent.com/SyedMuhammadArsalanShah/DataScienceCourse/refs/heads/master/00Datasets/CSV%20Datasets/mental_health_survey.csv")

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,2015-09-12 11:17:21,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
1255,2015-09-26 01:07:35,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
1256,2015-11-07 12:36:58,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
1257,2015-11-30 21:25:06,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
1258,2016-02-01 23:04:31,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

In [34]:
data=pd.read_json("https://api.alquran.cloud/v1/surah")
data

df=pd.json_normalize(data["data"])
df

,number,name,englishName,englishNameTranslation,numberOfAyahs,revelationType
0,1,سُورَةُ ٱلْفَاتِحَةِ,Al-Faatiha,The Opening,7,Meccan
1,2,سُورَةُ البَقَرَةِ,Al-Baqara,The Cow,286,Medinan
2,3,سُورَةُ آلِ عِمۡرَانَ,Aal-i-Imraan,The Family of Imraan,200,Medinan
3,4,سُورَةُ النِّسَاءِ,An-Nisaa,The Women,176,Medinan
4,5,سُورَةُ المَائـِدَةِ,Al-Maaida,The Table,120,Medinan
...,...,...,...,...,...,...
109,110,سُورَةُ النَّصۡرِ,An-Nasr,Divine Support,3,Medinan
110,111,سُورَةُ المَسَدِ,Al-Masad,The Palm Fibre,5,Meccan
111,112,سُورَةُ الإِخۡلَاصِ,Al-Ikhlaas,Sincerity,4,Meccan
112,113,سُورَةُ الفَلَقِ,Al-Falaq,The Dawn,5,Meccan
113,114,سُورَةُ النَّاسِ,An-Naas,Mankind,6,Meccan

In [43]:
df.head()
df.head(50)
df.tail(14)
df.info()
df.describe()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   number                  114 non-null    int64
 1   name                    114 non-null    object
 2   englishName             114 non-null    object
 3   englishNameTranslation  114 non-null    object
 4   numberOfAyahs           114 non-null    int64
 5   revelationType          114 non-null    object
dtypes: int64(2), object(4)
memory usage: 5.5+ KB

(114, 6)

In [46]:
df["name"]
df[["name", "numberOfAyahs"]]

                       name  numberOfAyahs
0      سُورَةُ ٱلْفَاتِحَةِ              7
1        سُورَةُ البَقَرَةِ            286
2    سُورَةُ آلِ عِمۡرَانَ            200
3        سُورَةُ النِّسَاءِ            176
4      سُورَةُ المَائـِدَةِ            120
..                      ...            ...
109       سُورَةُ النَّصۡرِ              3
110        سُورَةُ المَسَدِ              5
111     سُورَةُ الإِخۡلَاصِ              4
112        سُورَةُ الفَلَقِ              5
113        سُورَةُ النَّاسِ              6

[114 rows x 2 columns]

In [64]:
df.loc[0]
df.iloc[113]


df.loc[0,"name"]

df.loc[0,["name", "numberOfAyahs"]]


df.iloc[0:2]

df.iloc[0:,1:4]

# row , cols
df.iloc[0:2,0:3]

   number                  name englishName
0       1  سُورَةُ ٱلْفَاتِحَةِ  Al-Faatiha
1       2    سُورَةُ البَقَرَةِ   Al-Baqara

In [68]:
df.at[0, "name"]
df.iat[0,2]

'Al-Faatiha'

In [73]:
df.query("numberOfAyahs > 100 and revelationType == 'Meccan'")
df[df["numberOfAyahs"]<50]

,number,name,englishName,englishNameTranslation,numberOfAyahs,revelationType
0,1,سُورَةُ ٱلْفَاتِحَةِ,Al-Faatiha,The Opening,7,Meccan
12,13,سُورَةُ الرَّعۡدِ,Ar-Ra'd,The Thunder,43,Medinan
30,31,سُورَةُ لُقۡمَانَ,Luqman,Luqman,34,Meccan
31,32,سُورَةُ السَّجۡدَةِ,As-Sajda,The Prostration,30,Meccan
34,35,سُورَةُ فَاطِرٍ,Faatir,The Originator,45,Meccan
...,...,...,...,...,...,...
109,110,سُورَةُ النَّصۡرِ,An-Nasr,Divine Support,3,Medinan
110,111,سُورَةُ المَسَدِ,Al-Masad,The Palm Fibre,5,Meccan
111,112,سُورَةُ الإِخۡلَاصِ,Al-Ikhlaas,Sincerity,4,Meccan
112,113,سُورَةُ الفَلَقِ,Al-Falaq,The Dawn,5,Meccan
113,114,سُورَةُ النَّاسِ,An-Naas,Mankind,6,Meccan

In [84]:
df.isnull().sum()
df.dropna()
df.fillna(0)
df.duplicated()
df.drop_duplicates()

,number,name,englishName,englishNameTranslation,numberOfAyahs,revelationType
0,1,سُورَةُ ٱلْفَاتِحَةِ,Al-Faatiha,The Opening,7,Meccan
1,2,سُورَةُ البَقَرَةِ,Al-Baqara,The Cow,286,Medinan
2,3,سُورَةُ آلِ عِمۡرَانَ,Aal-i-Imraan,The Family of Imraan,200,Medinan
3,4,سُورَةُ النِّسَاءِ,An-Nisaa,The Women,176,Medinan
4,5,سُورَةُ المَائـِدَةِ,Al-Maaida,The Table,120,Medinan
...,...,...,...,...,...,...
109,110,سُورَةُ النَّصۡرِ,An-Nasr,Divine Support,3,Medinan
110,111,سُورَةُ المَسَدِ,Al-Masad,The Palm Fibre,5,Meccan
111,112,سُورَةُ الإِخۡلَاصِ,Al-Ikhlaas,Sincerity,4,Meccan
112,113,سُورَةُ الفَلَقِ,Al-Falaq,The Dawn,5,Meccan
113,114,سُورَةُ النَّاسِ,An-Naas,Mankind,6,Meccan

In [86]:
df["englishName"].str.upper()

0        AL-FAATIHA
1         AL-BAQARA
2      AAL-I-IMRAAN
3          AN-NISAA
4         AL-MAAIDA
           ...
109         AN-NASR
110        AL-MASAD
111      AL-IKHLAAS
112        AL-FALAQ
113         AN-NAAS
Name: englishName, Length: 114, dtype: object